<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NigerianBanksSeeder extends Seeder
{
    /**
     * Seed all Nigerian banks
     * Source: CBN approved banks list + PalmPay supported banks
     */
    public function run()
    {
        $banks = [
            // Commercial Banks
            ['name' => 'Access Bank', 'code' => '044'],
            ['name' => 'Citibank Nigeria', 'code' => '023'],
            ['name' => 'Ecobank Nigeria', 'code' => '050'],
            ['name' => 'Fidelity Bank', 'code' => '070'],
            ['name' => 'First Bank of Nigeria', 'code' => '011'],
            ['name' => 'First City Monument Bank (FCMB)', 'code' => '214'],
            ['name' => 'Globus Bank', 'code' => '00103'],
            ['name' => 'Guaranty Trust Bank (GTBank)', 'code' => '058'],
            ['name' => 'Heritage Bank', 'code' => '030'],
            ['name' => 'Keystone Bank', 'code' => '082'],
            ['name' => 'Polaris Bank', 'code' => '076'],
            ['name' => 'Providus Bank', 'code' => '101'],
            ['name' => 'Stanbic IBTC Bank', 'code' => '221'],
            ['name' => 'Standard Chartered Bank', 'code' => '068'],
            ['name' => 'Sterling Bank', 'code' => '232'],
            ['name' => 'SunTrust Bank', 'code' => '100'],
            ['name' => 'Titan Trust Bank', 'code' => '102'],
            ['name' => 'Union Bank of Nigeria', 'code' => '032'],
            ['name' => 'United Bank for Africa (UBA)', 'code' => '033'],
            ['name' => 'Unity Bank', 'code' => '215'],
            ['name' => 'Wema Bank', 'code' => '035'],
            ['name' => 'Zenith Bank', 'code' => '057'],

            // Microfinance Banks
            ['name' => 'ALAT by WEMA', 'code' => '035A'],
            ['name' => 'Coronation Merchant Bank', 'code' => '559'],
            ['name' => 'Jaiz Bank', 'code' => '301'],
            ['name' => 'Kuda Bank', 'code' => '50211'],
            ['name' => 'Lotus Bank', 'code' => '303'],
            ['name' => 'Parallex Bank', 'code' => '526'],
            ['name' => 'Rand Merchant Bank', 'code' => '502'],
            ['name' => 'Rubies MFB', 'code' => '125'],
            ['name' => 'Sparkle Microfinance Bank', 'code' => '51310'],
            ['name' => 'TCF MFB', 'code' => '51211'],
            ['name' => 'VFD Microfinance Bank', 'code' => '566'],

            // Digital Banks & Fintechs
            ['name' => 'Carbon', 'code' => '565'],
            ['name' => 'Eyowo', 'code' => '50126'],
            ['name' => 'FairMoney Microfinance Bank', 'code' => '51318'],
            ['name' => 'GoMoney', 'code' => '100022'],
            ['name' => 'Moniepoint MFB', 'code' => '50515'],
            ['name' => 'OPay', 'code' => '999992'],
            ['name' => 'PalmPay', 'code' => '999991'],
            ['name' => 'Paga', 'code' => '100002'],
            ['name' => 'Paycom', 'code' => '100004'],
            ['name' => 'Renmoney MFB', 'code' => '50767'],
            ['name' => 'Rubies MFB', 'code' => '125'],
            ['name' => 'Sparkle', 'code' => '51310'],
            ['name' => 'TagPay', 'code' => '100023'],
            ['name' => 'VBank', 'code' => '51314'],

            // Additional Banks
            ['name' => '9mobile 9Payment Service Bank', 'code' => '120001'],
            ['name' => 'Abbey Mortgage Bank', 'code' => '801'],
            ['name' => 'Above Only MFB', 'code' => '51204'],
            ['name' => 'Abulesoro MFB', 'code' => '51312'],
            ['name' => 'Accion Microfinance Bank', 'code' => '602'],
            ['name' => 'Ahmadu Bello University Microfinance Bank', 'code' => '50036'],
            ['name' => 'Airtel Smartcash PSB', 'code' => '120004'],
            ['name' => 'AKU Microfinance Bank', 'code' => '51336'],
            ['name' => 'ALAT by WEMA', 'code' => '035A'],
            ['name' => 'Amju Unique MFB', 'code' => '50926'],
            ['name' => 'ASO Savings and Loans', 'code' => '401'],
            ['name' => 'Astrapolaris MFB', 'code' => 'MFB50094'],
            ['name' => 'Bainescredit MFB', 'code' => '51229'],
            ['name' => 'Bowen Microfinance Bank', 'code' => '50931'],
            ['name' => 'Branch International Financial Services Limited', 'code' => 'FC40163'],
            ['name' => 'Cellulant', 'code' => '317'],
            ['name' => 'Chanelle Microfinance Bank Limited', 'code' => '50171'],
            ['name' => 'Chikum Microfinance bank', 'code' => '312'],
            ['name' => 'Citi Bank', 'code' => '023'],
            ['name' => 'Consumer Microfinance Bank', 'code' => '50910'],
            ['name' => 'Corestep MFB', 'code' => '50204'],
            ['name' => 'Coronation Merchant Bank', 'code' => '559'],
            ['name' => 'County Finance Limited', 'code' => 'FC40128'],
            ['name' => 'Crescent MFB', 'code' => '51297'],
            ['name' => 'Dot Microfinance Bank', 'code' => '50162'],
            ['name' => 'Ecobank Xpress Account', 'code' => '307'],
            ['name' => 'Ekondo Microfinance Bank', 'code' => '562'],
            ['name' => 'Ekimogun MFB', 'code' => '50263'],
            ['name' => 'Fairmoney Microfinance Bank', 'code' => '51318'],
            ['name' => 'Fidelity Mobile', 'code' => '318'],
            ['name' => 'Firmus MFB', 'code' => '51314'],
            ['name' => 'First Multiple MFB', 'code' => '50746'],
            ['name' => 'FSDH Merchant Bank Limited', 'code' => '501'],
            ['name' => 'Gateway Mortgage Bank LTD', 'code' => '812'],
            ['name' => 'Globus Bank', 'code' => '00103'],
            ['name' => 'GoMoney', 'code' => '100022'],
            ['name' => 'Greenwich Merchant Bank', 'code' => '562'],
            ['name' => 'Hackman Microfinance Bank', 'code' => '51251'],
            ['name' => 'Hasal Microfinance Bank', 'code' => '50383'],
            ['name' => 'Hopepsb', 'code' => '120002'],
            ['name' => 'Ibile Microfinance Bank', 'code' => '51244'],
            ['name' => 'Ikoyi Osun MFB', 'code' => '50439'],
            ['name' => 'Ilaro Poly Microfinance Bank', 'code' => '50442'],
            ['name' => 'Imowo MFB', 'code' => '50453'],
            ['name' => 'Infinity MFB', 'code' => '50457'],
            ['name' => 'Jaiz Bank', 'code' => '301'],
            ['name' => 'Kadpoly MFB', 'code' => '50502'],
            ['name' => 'Kredi Money MFB LTD', 'code' => '50200'],
            ['name' => 'Kuda Bank', 'code' => '50211'],
            ['name' => 'Lagos Building Investment Company Plc.', 'code' => '90052'],
            ['name' => 'Links MFB', 'code' => '50549'],
            ['name' => 'Living Trust Mortgage Bank', 'code' => '031'],
            ['name' => 'Lotus Bank', 'code' => '303'],
            ['name' => 'Mayfair MFB', 'code' => '50563'],
            ['name' => 'Mint MFB', 'code' => '50304'],
            ['name' => 'Moniepoint MFB', 'code' => '50515'],
            ['name' => 'MTN Momo PSB', 'code' => '120003'],
            ['name' => 'Mutual Trust Microfinance Bank', 'code' => '51293'],
            ['name' => 'NPF Microfinance Bank', 'code' => '552'],
            ['name' => 'Optimus Bank Limited', 'code' => '107'],
            ['name' => 'Paga', 'code' => '100002'],
            ['name' => 'PalmPay', 'code' => '999991'],
            ['name' => 'Parallex Bank', 'code' => '526'],
            ['name' => 'Parkway - ReadyCash', 'code' => '311'],
            ['name' => 'Paycom', 'code' => '100004'],
            ['name' => 'Peace Microfinance Bank', 'code' => '50743'],
            ['name' => 'Personal Trust MFB', 'code' => '51146'],
            ['name' => 'Petra Mircofinance Bank Plc', 'code' => '50746'],
            ['name' => 'Polaris Bank', 'code' => '076'],
            ['name' => 'Polyunwana MFB', 'code' => '50864'],
            ['name' => 'PremiumTrust Bank', 'code' => '105'],
            ['name' => 'Providus Bank', 'code' => '101'],
            ['name' => 'QuickFund MFB', 'code' => '51293'],
            ['name' => 'Rand Merchant Bank', 'code' => '502'],
            ['name' => 'Refuge Mortgage Bank', 'code' => '90067'],
            ['name' => 'Renmoney MFB', 'code' => '50767'],
            ['name' => 'Rigo Microfinance Bank Limited', 'code' => '51286'],
            ['name' => 'ROCKSHIELD MICROFINANCE BANK', 'code' => '50767'],
            ['name' => 'Rubies MFB', 'code' => '125'],
            ['name' => 'Safe Haven MFB', 'code' => '51113'],
            ['name' => 'Safe Haven Microfinance Bank Limited', 'code' => '51113'],
            ['name' => 'SAGE GREY FINANCE LIMITED', 'code' => 'FC40074'],
            ['name' => 'Shield MFB', 'code' => '50582'],
            ['name' => 'Solid Allianze MFB', 'code' => '51062'],
            ['name' => 'Solid Rock MFB', 'code' => '50800'],
            ['name' => 'Sparkle Microfinance Bank', 'code' => '51310'],
            ['name' => 'Stanbic IBTC @ease wallet', 'code' => '304'],
            ['name' => 'Stellas MFB', 'code' => '51253'],
            ['name' => 'Sterling Mobile', 'code' => '326'],
            ['name' => 'Suntrust Bank', 'code' => '100'],
            ['name' => 'Supreme MFB', 'code' => '50968'],
            ['name' => 'TAJ Bank', 'code' => '302'],
            ['name' => 'Tanadi Microfinance Bank', 'code' => '090560'],
            ['name' => 'Tangerine Money', 'code' => '51269'],
            ['name' => 'TCF MFB', 'code' => '51211'],
            ['name' => 'Teasy Mobile', 'code' => '100010'],
            ['name' => 'Titan Trust Bank', 'code' => '102'],
            ['name' => 'Trident Microfinance Bank', 'code' => '50871'],
            ['name' => 'Trustbond Mortgage Bank', 'code' => '523'],
            ['name' => 'Trustfund Microfinance Bank', 'code' => '51297'],
            ['name' => 'U&C Microfinance Bank Ltd (U AND C MFB)', 'code' => '50840'],
            ['name' => 'Uhuru MFB', 'code' => '51322'],
            ['name' => 'Unaab Microfinance Bank Limited', 'code' => '50870'],
            ['name' => 'Unical MFB', 'code' => '50871'],
            ['name' => 'Unilag Microfinance Bank', 'code' => '51316'],
            ['name' => 'VFD Microfinance Bank Limited', 'code' => '566'],
            ['name' => 'Virtue MFB', 'code' => '51332'],
            ['name' => 'Visa Microfinance Bank', 'code' => '51335'],
            ['name' => 'Waya Microfinance Bank', 'code' => '51355'],
            ['name' => 'Wetland Microfinance Bank', 'code' => '50389'],
            ['name' => 'Xslnce Microfinance Bank', 'code' => '50383'],
            ['name' => 'Yes MFB', 'code' => '51304'],
            ['name' => 'Zenith Mobile', 'code' => '322'],
        ];

        foreach ($banks as $bank) {
            DB::table('banks')->updateOrInsert(
                ['code' => $bank['code']],
                [
                    'name' => $bank['name'],
                    'active' => true,
                    'created_at' => now(),
                    'updated_at' => now()
                ]
            );
        }

        $this->command->info('✅ Seeded ' . count($banks) . ' Nigerian banks');
    }
}
