<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Transaction History Report</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            font-size: 10px;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #01b875;
            padding-bottom: 10px;
        }

        .header h1 {
            color: #01b875;
            margin: 0;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0 0;
            color: #666;
            font-size: 12px;
        }

        .report-info {
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
        }

        .report-info div {
            width: 45%;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }

        th {
            background-color: #f8f9fa;
            color: #01b875;
            font-weight: bold;
            text-align: left;
            padding: 8px;
            border-bottom: 1px solid #dee2e6;
            text-transform: uppercase;
            font-size: 9px;
        }

        td {
            padding: 8px;
            border-bottom: 1px solid #eee;
            vertical-align: top;
        }

        .amount {
            text-align: right;
            font-weight: bold;
        }

        .status-success {
            color: #01b875;
        }

        .status-failed {
            color: #ff5630;
        }

        .status-pending {
            color: #ffab00;
        }

        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            text-align: center;
            font-size: 8px;
            color: #999;
            border-top: 1px solid #eee;
            padding-top: 5px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>PointWave</h1>
        <p>System Transaction History Report</p>
    </div>

    <div class="report-info">
        <div>
            <strong>Report Date:</strong> {{ date('d M Y, H:i:s') }}<br>
            <strong>Generated By:</strong> Administrator
        </div>
        <div style="text-align: right;">
            <strong>Period:</strong> {{ $start_date ?? 'All Time' }} to {{ $end_date ?? date('d M Y') }}<br>
            <strong>Total Transactions:</strong> {{ count($transactions) }}
        </div>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Order ID</th>
                <th>Type</th>
                <th>Merchant Ref</th>
                <th>Payer</th>
                <th>Company</th>
                <th>Status</th>
                <th class="amount">Amount (₦)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $tx)
                <tr>
                    <td>{{ date('d/m/y H:i', strtotime($tx->Date)) }}</td>
                    <td>{{ $tx->TransOrderNo }}</td>
                    <td>{{ ucfirst($tx->OrderType) }}</td>
                    <td>{{ $tx->MerchantOrderNo ?? '-' }}</td>
                    <td>{{ $tx->Customer ?? '-' }}</td>
                    <td>{{ $tx->Company ?? 'System' }}</td>
                    <td>
                        <span class="status-{{ strtolower($tx->Status) }}">
                            {{ ucfirst($tx->Status) }}
                        </span>
                    </td>
                    <td class="amount">{{ number_format($tx->Amount, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        &copy; {{ date('Y') }} PointWave. This is a computer-generated report.
    </div>
</body>

</html>